<?php

use Illuminate\Database\Seeder;

use App\Animal;

class AnimalTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $data = array(
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 1,
              'N_DARP' => "1",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80), 
              //'Perimetre_Torax' => rand(40, 80),  
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 2,
              'N_DARP' => "2",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 3,
              'N_DARP' => "3",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 4,
              'N_DARP' => "4",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80), 
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 5,
              'N_DARP' => "5",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 6,
              'N_DARP' => "6",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80), 
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 7,
              'N_DARP' => "7",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 8,
              'N_DARP' => "8",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 9,
              'N_DARP' => "9",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 10,
              'N_DARP' => "10",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 11,
              'N_DARP' => "11",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 12,
              'N_DARP' => "12",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 13,
              'N_DARP' => "13",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 14,
              'N_DARP' => "14",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 15,
              'N_DARP' => "15",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 16,
              'N_DARP' => "16",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 17,
              'N_DARP' => "17",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 18,
              'N_DARP' => "18",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 19,
              'N_DARP' => "19",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 20,
              'N_DARP' => "20",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
           [
              'ID_GRANJA' => rand(1,4),
              'N_Explotacio' => 21,
              'N_DARP' => "21",  
              'Data_Naixement' => $this->randomDate(),  
              'Data_Mort' => null,
              'Data_Deslletament' =>new DateTime,
              'Data_Cremada_Banyes' =>new DateTime,
              'Metode_Cremada'=> "flamethrower",
              'Contorn_Centimetres' => rand(50, 500),
              'Litres_Calostra' => rand(1,10),
              'Preses_Calostra' => 5,
              'sexe'=> 'F',
              'Pes_Actual'=> rand(3, 80),
              //'Perimetre_Torax' => rand(40, 80),
              'Ruta_Imatge' => null 
            ],
       );
       
       Animal::insert($data);
    }
    
    
    private function randomDate(){
        $y = rand(2000, 2019);
        $m = rand(1,12);
        $d = rand(1,30);
        
        return new DateTime("".$y."-".$m."-".$d);
    }
}
